### PR TITLE
fix docs of meshery-nighthawk repos readme file broken images links

### LINKED ISSUE #28: [Docs] Readme: Broken Images
#### Current Behavior
Images in the readme are in need of having their links fixed.

#### Expected Behavior
No broken image links in [readme](https://github.com/meshery/meshery-nighthawk/edit/master/README.md).

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by ranjeetxsingh**
**Description**

This PR fixes #28  [docs] readme : broken images

**Notes for Reviewers**
src url for images is changed to reflect correct path with same logos

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by gyohuangxin — APPROVED** [review]
LGTM. Thanks for your PR.

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
@ranjeetxsingh, thanks! 

@gyohuangxin, teamwork. 🙂 Please merge at-will.

**Comment by gyohuangxin** [comment]
@leecalcote Sure, but I don't have the permission to merge it, can you give me it in this repo?

**Comment by leecalcote** [comment]
Yay! @ranjeetxsingh 🎈

**Pull request merged**
