### PR TITLE
Fix error 'Error closing file: invalid argument'

### PR DESCRIPTION
**Pull request by gyohuangxin**
**Description**

It reads `./build/meshmodel_metadata.json` but the current filename is `./build/model_metadata.json`, so this PR is to fix it.
https://github.com/meshery/meshery-nighthawk/blob/f9ce9271795e55e177216bfa4511a436d1e127ef/build/config.go#L50

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by MUzairS15 — CHANGES_REQUESTED** [review]
@gyohuangxin Thanks for raising the fix.
But it needs a slight change.
We are moving away from usage of `meshmodel` to `model`.
Hence instead of renaming file to `build/meshmodel_metadata.json` change the code to look for `build/model_metadata.json`.

Also, wherever you find usage of `meshmodel`, please rename to `model`.

**Comment by gyohuangxin** [comment]
@MUzairS15 Thanks for the reminder, I've changed the code to look for build/model_metadata.json. And I found that github.com/layer5io/meshery-adapter-library/adapter still uses MeshModel to name functions, so we can replace them once github.com/layer5io/meshery-adapter-library/adapter has changed to use Model instead of MeshModel.

**Comment by leecalcote** [comment]
> @MUzairS15 Thanks for the reminder, I've changed the code to look for build/model_metadata.json. And I found that github.com/layer5io/meshery-adapter-library/adapter still uses MeshModel to name functions, so we can replace them once github.com/layer5io/meshery-adapter-library/adapter has changed to use Model instead of MeshModel.

Yes, please, @gyohuangxin

**Review by MUzairS15 — APPROVED** [review]

**Comment by MUzairS15** [comment]
> @MUzairS15 Thanks for the reminder, I've changed the code to look for build/model_metadata.json. And I found that github.com/layer5io/meshery-adapter-library/adapter still uses MeshModel to name functions, so we can replace them once github.com/layer5io/meshery-adapter-library/adapter has changed to use Model instead of MeshModel.

Thanks!.

**Pull request merged**
