### PR TITLE
Add language\golang GitHub Issue label to GitHub issue templates for features and bugs

### PR DESCRIPTION
**Pull request by RyanbowZ**
**Description**

This PR updates the default labels of features and bugs report templates to be language/golang as requested.

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by gyohuangxin** [comment]
@RyanbowZ Thanks for your first contribution, it looks good to me.

Fix #19.

**Review by gyohuangxin — APPROVED** [review]

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thank you, gents. 

@RyanbowZ, will you please retain the original labels, while adding the Golang label as a second label?

**Comment by RyanbowZ** [comment]
> Thank you, gents.
> 
> @RyanbowZ, will you please retain the original labels, while adding the Golang label as a second label?

Of course, I will do that.

**Comment by RyanbowZ** [comment]
Hi I have updated it and now awaiting your approval

**Review by gyohuangxin — APPROVED** [review]

**Comment by gyohuangxin** [comment]
@leecalcote Can you approve it?

**Review by leecalcote — APPROVED** [review]
Thank you, gents. 👍

**Comment by leecalcote** [comment]
Yay, @RyanbowZ! 🎈

**Pull request merged**
