### PR TITLE
Add SMPModel in /templates/meshmodel

### PR DESCRIPTION
**Pull request by gyohuangxin**
**Description**

This PR related to https://github.com/meshery/meshery-nighthawk/issues/27#issuecomment-1956627115

**Notes for Reviewers**

- Generated SMP spec json file manually from https://github.com/service-mesh-performance/service-mesh-performance.git, and copied to /templates/meshmodel.
- Created the manifests/charts/crds.yaml to define performance profile in the future.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by gyohuangxin** [comment]
@MUzairS15 @leecalcote  This is the initial PR based on my understanding, I don't know if it is correct, please forgive me I haven't figured out the Meshery Model very well, please correct me if I'm wrong. Thanks!

**Comment by leecalcote** [comment]
I'm very excited about this, @gyohuangxin. 😀

**Comment by leecalcote** [comment]
We're in need of having `RegisterMeshModelComponents` changed to `RegisterMeshModelComponents` inside of the Meshery Adapter Library. Let's do what we can to get away from `MeshModel` over to `Model`.

**Review by MUzairS15 — COMMENTED** [review]
Nice to see the progress, @gyohuangxin.
The definitions violate the component definition schemas defined in [meshery/schemas](https://github.com/meshery/schemas/blob/master/models/component.json).

**Comment by MUzairS15** [comment]
I will update the components so that we can move forward.

**Comment by gyohuangxin** [comment]
@MUzairS15 Thanks for your help!

**Review by gyohuangxin — COMMENTED** [review]
@MUzairS15 I see you changed the metadata.json and deleted the service_mesh_performance.json, do we should need to change or delete the service_mesh.json?

**Comment by MUzairS15** [comment]
Oh yes, I missed that.

**Review by MUzairS15 — APPROVED** [review]

**Pull request merged**
